package celerbi.mirageprojector.network;

import celerbi.mirageprojector.MirageProjector;
import net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent;
import net.neoforged.neoforge.network.registration.PayloadRegistrar;

public final class ModNetworking {
    private ModNetworking() {
    }

    public static void registerPayloads(RegisterPayloadHandlersEvent event) {
        PayloadRegistrar registrar = event.registrar(MirageProjector.NETWORK_PROTOCOL);

        registrar.playToServer(
                UpdateProjectorPayload.TYPE,
                UpdateProjectorPayload.STREAM_CODEC,
                UpdateProjectorPayload::handle
        );
        registrar.playToServer(
                OpenEntityWorkspacePayload.TYPE,
                OpenEntityWorkspacePayload.STREAM_CODEC,
                OpenEntityWorkspacePayload::handle
        );
        registrar.playToServer(
                OpenImageWorkspacePayload.TYPE,
                OpenImageWorkspacePayload.STREAM_CODEC,
                OpenImageWorkspacePayload::handle
        );
        registrar.playToServer(
                OpenItemWorkspacePayload.TYPE,
                OpenItemWorkspacePayload.STREAM_CODEC,
                OpenItemWorkspacePayload::handle
        );
        registrar.playToServer(
                OpenBannerWorkspacePayload.TYPE,
                OpenBannerWorkspacePayload.STREAM_CODEC,
                OpenBannerWorkspacePayload::handle
        );
        registrar.playToServer(
                BannerWorkspaceActionPayload.TYPE,
                BannerWorkspaceActionPayload.STREAM_CODEC,
                BannerWorkspaceActionPayload::handle
        );
        registrar.playToServer(
                UpdateImageWorkspacePayload.TYPE,
                UpdateImageWorkspacePayload.STREAM_CODEC,
                UpdateImageWorkspacePayload::handle
        );
        registrar.playToServer(
                SetProjectionSourcePayload.TYPE,
                SetProjectionSourcePayload.STREAM_CODEC,
                SetProjectionSourcePayload::handle
        );
        registrar.playToServer(
                SetProjectionEnabledPayload.TYPE,
                SetProjectionEnabledPayload.STREAM_CODEC,
                SetProjectionEnabledPayload::handle
        );
        registrar.playToServer(
                OpenProjectorWorkspacePayload.TYPE,
                OpenProjectorWorkspacePayload.STREAM_CODEC,
                OpenProjectorWorkspacePayload::handle
        );
        registrar.playToServer(
                EntityWorkspaceActionPayload.TYPE,
                EntityWorkspaceActionPayload.STREAM_CODEC,
                EntityWorkspaceActionPayload::handle
        );
        registrar.playToServer(
                UploadAssetChunkPayload.TYPE,
                UploadAssetChunkPayload.STREAM_CODEC,
                UploadAssetChunkPayload::handle
        );
        registrar.playToServer(
                RequestAssetPayload.TYPE,
                RequestAssetPayload.STREAM_CODEC,
                RequestAssetPayload::handle
        );
        registrar.playToServer(
                RequestMirageLightChunkPayload.TYPE,
                RequestMirageLightChunkPayload.STREAM_CODEC,
                RequestMirageLightChunkPayload::handle
        );
        registrar.playToClient(
                DownloadAssetChunkPayload.TYPE,
                DownloadAssetChunkPayload.STREAM_CODEC,
                DownloadAssetChunkPayload::handle
        );
        registrar.playToClient(
                AssetUploadAckPayload.TYPE,
                AssetUploadAckPayload.STREAM_CODEC,
                AssetUploadAckPayload::handle
        );
        registrar.playToClient(
                OpenDebugHandbookPayload.TYPE,
                OpenDebugHandbookPayload.STREAM_CODEC,
                OpenDebugHandbookPayload::handle
        );
        registrar.playToClient(
                MirageLightChunkSnapshotPayload.TYPE,
                MirageLightChunkSnapshotPayload.STREAM_CODEC,
                MirageLightChunkSnapshotPayload::handle
        );
        registrar.playToClient(
                MirageLightChunkRevisionManifestPayload.TYPE,
                MirageLightChunkRevisionManifestPayload.STREAM_CODEC,
                MirageLightChunkRevisionManifestPayload::handle
        );
        registrar.playToClient(
                PortableProjectorStatePayload.TYPE,
                PortableProjectorStatePayload.STREAM_CODEC,
                PortableProjectorStatePayload::handle
        );
        registrar.playToServer(
                ShoulderEquipmentActionPayload.TYPE,
                ShoulderEquipmentActionPayload.STREAM_CODEC,
                ShoulderEquipmentActionPayload::handle
        );
        registrar.playToClient(
                ShoulderEquipmentStatePayload.TYPE,
                ShoulderEquipmentStatePayload.STREAM_CODEC,
                ShoulderEquipmentStatePayload::handle
        );
        registrar.playToClient(
                ShoulderEquipmentInventoryPayload.TYPE,
                ShoulderEquipmentInventoryPayload.STREAM_CODEC,
                ShoulderEquipmentInventoryPayload::handle
        );
        registrar.playToClient(
                ShoulderEquipmentCursorPayload.TYPE,
                ShoulderEquipmentCursorPayload.STREAM_CODEC,
                ShoulderEquipmentCursorPayload::handle
        );
        registrar.playToClient(
                OpenScanCodexPayload.TYPE,
                OpenScanCodexPayload.STREAM_CODEC,
                OpenScanCodexPayload::handle
        );
        registrar.playToServer(
                ScanCodexActionPayload.TYPE,
                ScanCodexActionPayload.STREAM_CODEC,
                ScanCodexActionPayload::handle
        );
        registrar.playToClient(
                OpenLecternScanCodexPayload.TYPE,
                OpenLecternScanCodexPayload.STREAM_CODEC,
                OpenLecternScanCodexPayload::handle
        );
        registrar.playToServer(
                LecternScanCodexActionPayload.TYPE,
                LecternScanCodexActionPayload.STREAM_CODEC,
                LecternScanCodexActionPayload::handle
        );
        registrar.playToServer(
                OpenPortableDeviceMenuPayload.TYPE,
                OpenPortableDeviceMenuPayload.STREAM_CODEC,
                OpenPortableDeviceMenuPayload::handle
        );
        registrar.playToServer(
                PortableDeviceActionPayload.TYPE,
                PortableDeviceActionPayload.STREAM_CODEC,
                PortableDeviceActionPayload::handle
        );
        registrar.playToServer(
                LightProjectorActionPayload.TYPE,
                LightProjectorActionPayload.STREAM_CODEC,
                LightProjectorActionPayload::handle
        );
        registrar.playToClient(
                OpenPresentationRemotePayload.TYPE,
                OpenPresentationRemotePayload.STREAM_CODEC,
                OpenPresentationRemotePayload::handle
        );
        registrar.playToServer(
                PresentationRemoteActionPayload.TYPE,
                PresentationRemoteActionPayload.STREAM_CODEC,
                PresentationRemoteActionPayload::handle
        );
        registrar.playToServer(
                UnpairPresentationRemotePayload.TYPE,
                UnpairPresentationRemotePayload.STREAM_CODEC,
                UnpairPresentationRemotePayload::handle
        );
    }
}
